// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MZZkA0aDMXgflT6LpE4QEoec21SJ-aw',
    appId: '1:800635303249:web:3e4eabdb1e452d5fc3cf70',
    messagingSenderId: '800635303249',
    projectId: 'recipe-explorer-pro',
    authDomain: 'recipe-explorer-pro.firebaseapp.com',
    storageBucket: 'recipe-explorer-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTKBezNQChleCbDLJwdYCNTxbAAyyJcDA',
    appId: '1:800635303249:android:f8ad5a89cb890c1dc3cf70',
    messagingSenderId: '800635303249',
    projectId: 'recipe-explorer-pro',
    storageBucket: 'recipe-explorer-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKxIJZXxnhdElKEnOclM-1IqhjrKJIog',
    appId: '1:800635303249:ios:d857e90a868532c2c3cf70',
    messagingSenderId: '800635303249',
    projectId: 'recipe-explorer-pro',
    storageBucket: 'recipe-explorer-pro.firebasestorage.app',
    iosBundleId: 'com.recipeexplorerpro.recipeExplorerPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKxIJZXxnhdElKEnOclM-1IqhjrKJIog',
    appId: '1:800635303249:ios:d857e90a868532c2c3cf70',
    messagingSenderId: '800635303249',
    projectId: 'recipe-explorer-pro',
    storageBucket: 'recipe-explorer-pro.firebasestorage.app',
    iosBundleId: 'com.recipeexplorerpro.recipeExplorerPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2MZZkA0aDMXgflT6LpE4QEoec21SJ-aw',
    appId: '1:800635303249:web:fa382cb6089b6f34c3cf70',
    messagingSenderId: '800635303249',
    projectId: 'recipe-explorer-pro',
    authDomain: 'recipe-explorer-pro.firebaseapp.com',
    storageBucket: 'recipe-explorer-pro.firebasestorage.app',
  );
}
